USE codeup_test_db;
DROP TABLE IF EXISTS albums;
CREATE TABLE IF NOT EXISTS albums(
id INT UNSIGNED NOT NULL,
artist VARCHAR(50) NOT NULL,
name VARCHAR(50) NOT NULL,
release_date INT,
sales FLOAT,
genre VARCHAR(25)
);